trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
 matrix:
 jdk10:
 jdk_version: "1.10"
 jdk11:
 jdk_version: "1.11"
 maxParallel: 2
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'